// POTRAITMANAGEMENT
export const POTRAITMANAGEMENT_TAB_CHANGE = 'POTRAITMANAGEMENT_TAB_CHANGE';
export const POTRAITMANAGEMENT_ADD_GRADE = 'POTRAITMANAGEMENT_ADD_GRADE';
export const POTRAITMANAGEMENT_DEL_GRADE = 'POTRAITMANAGEMENT_DEL_GRADE';