
// route name + module + action

export const GET_HONOR_LIST = 'GET_HONOR_LIST';
export const GET_GRADE_LIST = 'GET_GRADE_LIST';
export const GET_INTERNSHIP_LIST = 'GET_INTERNSHIP_LIST';
export const GET_ACADEMIC_LIST = 'GET_ACADEMIC_LIST';

// POTRAITMANAGEMENT
export const POTRAITMANAGEMENT_SHOW_EDIT_GRADE_DIALOG = 'POTRAITMANAGEMENT_SHOW_EDIT_GRADE_DIALOG';
export const POTRAITMANAGEMENT_CLOSE_EDIT_GRADE_DIALOG = 'POTRAITMANAGEMENT_CLOSE_EDIT_GRADE_DIALOG';
export const POTRAITMANAGEMENT_CHANGE_EDIT_GRADE_COURSENAME = 'POTRAITMANAGEMENT_CHANGE_EDIT_GRADE_COURSENAME';
export const POTRAITMANAGEMENT_CHANGE_EDIT_GRADE_SCORE = 'POTRAITMANAGEMENT_CHANGE_EDIT_GRADE_SCORE';
export const POTRAITMANAGEMENT_CHANGE_EDIT_GRADE_GPA = 'POTRAITMANAGEMENT_CHANGE_EDIT_GRADE_GPA';
export const POTRAITMANAGEMENT_CHANGE_EDIT_GRADE_ISMAJOR = 'POTRAITMANAGEMENT_CHANGE_EDIT_GRADE_ISMAJOR';
export const POTRAITMANAGEMENT_UPDATE_EDIT_GRADE = 'POTRAITMANAGEMENT_UPDATE_EDIT_GRADE';


export const POTRAITMANAGEMENT_TAB_CHANGE = 'POTRAITMANAGEMENT_TAB_CHANGE';
export const POTRAITMANAGEMENT_ADD_GRADE = 'POTRAITMANAGEMENT_ADD_GRADE';
export const POTRAITMANAGEMENT_DEL_GRADE = 'POTRAITMANAGEMENT_DEL_GRADE';
export const POTRAITMANAGEMENT_ADD_INTERNSHIP = 'POTRAITMANAGEMENT_ADD_INTERNSHIP';
export const POTRAITMANAGEMENT_DEL_INTERNSHIP = 'POTRAITMANAGEMENT_DEL_INTERNSHIP';
export const POTRAITMANAGEMENT_ADD_ACADEMIC = 'POTRAITMANAGEMENT_ADD_ACADEMIC';
export const POTRAITMANAGEMENT_DEL_ACADEMIC = 'POTRAITMANAGEMENT_DEL_ACADEMIC';
export const POTRAITMANAGEMENT_ADD_HONOR = 'POTRAITMANAGEMENT_ADD_HONOR';
export const POTRAITMANAGEMENT_DEL_HONOR = 'POTRAITMANAGEMENT_DEL_HONOR';